#!/usr/bin/env bash
set -e

if [[ $(id -u) -ne 0 ]] ; then echo "root/sudo privileges required" ; exit 1 ; fi

USER=app
THIS_DIR=$(readlink -f $(dirname "$0"))
SCRIPTS_DIR=$(dirname ${THIS_DIR})
PROJECT_DIR=$(dirname ${SCRIPTS_DIR})
START_FAB=${PROJECT_DIR}/start-fab.sh
START_QA=${PROJECT_DIR}/start-QA-server.sh
START_METABASE=${PROJECT_DIR}/start-QA-metabase.sh
SERVICES=( fab.service metabase.service )

if [[ -e ${START_FAB} ]];
then
    echo "Is ${PROJECT_DIR} the prod instance? Manually confirm and delete ${START_FAB} to continue setup. Exiting now";
    exit 1;
fi

read -p "FA_BUGSNAG_API_KEY=" FA_BUGSNAG_API_KEY
read -p "FA_ENV [qa|prod] =" FA_ENV
read -p "FA_IMPLEMENTATION_NAME [JSS|NHSRC] =" FA_IMPLEMENTATION_NAME
read -p "FA_NIN_API_KEY =" FA_NIN_API_KEY

echo "#!/bin/bash
export FA_BUGSNAG_API_KEY=${FA_BUGSNAG_API_KEY}
export FA_ENV=${FA_ENV}
export FA_IMPLEMENTATION_NAME=${FA_IMPLEMENTATION_NAME}
export FA_NIN_API_KEY=${FA_NIN_API_KEY}
make start_qa_server" > ${START_QA}
chown ${USER}:${USER} ${START_QA}
chmod 755 ${START_QA}
echo "Generated ${START_QA} ..."


echo '#!/bin/bash
export MB_JETTY_SSL="true"
export MB_JETTY_PORT="4001"
export MB_JETTY_SSL_Port="4000"
export MB_JETTY_SSL_Keystore="keystore.jks"
export MB_JETTY_SSL_Keystore_Password="<ENTER-PASSWORD>"
make start_metabase_server' > ${START_METABASE}
chown ${USER}:${USER} ${START_METABASE}
chmod 755 ${START_METABASE}
echo "Generated ${START_METABASE} ... "
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "!!! NOTE: Edit ${START_METABASE} and enter keystore password before executing !!!"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo

for SERVICE in "${SERVICES[@]}"
do
    sed -e "s;%WORKING_DIR%;${PROJECT_DIR};g" \
        -e "s;start-fab;start-QA-server;g" \
        -e "s;start-metabase;start-QA-metabase;g" \
        ${THIS_DIR}/${SERVICE}.template > /etc/systemd/system/qa-${SERVICE}
    echo "Created /etc/systemd/system/qa-${SERVICE} ..."
done

echo "Creating database \"facilities_assessment_qa\" ..."
cd ${PROJECT_DIR} && make create_qa_db


echo "systemctl daemon-reload ..."
systemctl daemon-reload
for SERVICE in "${SERVICES[@]}"
do
    systemctl enable qa-${SERVICE}
done
