#!/usr/bin/env bash
set -e

if ! [[ `command -v pip` ]]; then echo "Install 'pip'"; exit 1; fi
if [[ $(id -u) -ne 0 ]] ; then echo "root/sudo privileges required" ; exit 1 ; fi

./setup-service
./setup-cron

read -p "db username: " DB_USER
read -p "db password: " DB_PASS

su app -c "echo 'localhost:5432:facilities_assessment:${DB_USER}:${DB_PASS}' > ~/.pgpass"

pip install --upgrade pip
pip install awscli --upgrade

su app -c "aws configure"
chown -R app:app /home/app
