#!/usr/bin/env bash
set -e

if [[ $(id -u) -ne 0 ]] ; then echo "root/sudo privileges required" ; exit 1 ; fi

read -p "Name of backup directory in S3: " S3_BACKUP_DIRNAME
read -p "HEALTHCHECK_UUID = " HEALTHCHECK_UUID
read -p "db username: " DB_USER
read -p "db password: " DB_PASS

export S3_BACKUP_DIRNAME=${S3_BACKUP_DIRNAME}
export HEALTHCHECK_UUID=${HEALTHCHECK_UUID}

echo "export S3_BACKUP_DIRNAME=${S3_BACKUP_DIRNAME}
export HEALTHCHECK_UUID=${HEALTHCHECK_UUID}" >> /etc/environment

./setup-service
./setup-cron

su app -c "echo 'localhost:5432:facilities_assessment:${DB_USER}:${DB_PASS}' > ~/.pgpass"

apt install -y python-pip
pip install --upgrade pip
pip install awscli --upgrade

su app -c "aws configure"
chown -R app:app /home/app
